name : Deploy to Cloudflare Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly
          rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: |
          # ビルド時にカスタムプロファイルを使いたいのでwasm-packはlatestが必要
          cargo install --git https://github.com/rustwasm/wasm-pack.git
      - run: rustup run nightly wasm-pack build --target web --profile release-wasm
