name : Deploy to Cloudflare Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install nightly
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - run: |
          # ビルド時にカスタムプロファイルを使いたいのでwasm-packはlatestが必要
          cargo +nightly install --git https://github.com/rustwasm/wasm-pack.git
      - run: rustup run nightly wasm-pack build --target web --profile release-wasm
